# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc520f6c6cf6c85213775c58fdb8d573b6d4d3e72735a6c580a3f08eaae890acef33e904bf1bf3708e8fd1adc3afd7f538fd10b57990a05df201932e4babb9b6

test:
  secret_key_base: 6146d8ca44be0c327b5f2e5b683c66147ab1cd611f199fd08350fe4b5b6e8e5c5a3caf2d22462f34fc333062408629b22310fb2ada8a1bf7fe6cccc5bfd1f1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
